id: PD96BD644
initial_creation_type: input
source_metadata:
  title: Yuktidīpikā a commentary on Īśvarakṛṣṇa's Sāṃkhyakārikā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Sāṃkhya
  data entry: Dhaval Patel
  contribution to GRETIL: Dhaval Patel
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:59:40.924191'
last_modified_at: '2022-03-09T14:59:40.924204'
